name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: What do you want?
      description: Describe the feature briefly.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why?
      description: What problem does this solve?
    validations:
      required: true
